#define A_HELP                   31835
#define L_HELP                     933
#define A_LOCATION               31824
#define L_LOCATION                  11
#define A_SPACE                  31823
#define L_SPACE                      1
#define A_PROMPT                 31821
#define L_PROMPT                     2
#define A_QUIT                   31737
#define L_QUIT                      84
#define A_LOOK                   31715
#define L_LOOK                      22
#define A_COMMA                  31713
#define L_COMMA                      2
#define A_DONTSEE                31687
#define L_DONTSEE                   26
#define A_CANTLOOK               31665
#define L_CANTLOOK                  22
#define A_CANTENTER              31635
#define L_CANTENTER                 30
#define A_CANTOPEN               31608
#define L_CANTOPEN                  27
#define A_NOTCARRYING            31575
#define L_NOTCARRYING               33
#define A_NOSUCHOBJECT           31555
#define L_NOSUCHOBJECT              20
#define A_WHYTALK                31525
#define L_WHYTALK                   30
#define A_CANTUSE                31499
#define L_CANTUSE                   26
#define A_CANTUSEITEM            31460
#define L_CANTUSEITEM               39
#define A_RESPONSE               31442
#define L_RESPONSE                  18
#define A_INCORRECT              31424
#define L_INCORRECT                 18
#define A_CARRYTWO               31336
#define L_CARRYTWO                  88
#define A_ALREADYCARRYING        31299
#define L_ALREADYCARRYING           37
#define A_NOWCARRING             31277
#define L_NOWCARRING                22
#define A_EMPTYHANDS             31239
#define L_EMPTYHANDS                38
#define A_DROPPING               31223
#define L_DROPPING                  16
#define A_RETURNING              31162
#define L_RETURNING                 61
#define A_IDDQDMSG               31102
#define L_IDDQDMSG                  60
#define A_CONGRATS               31017
#define L_CONGRATS                  85
#define A_CANTGIVE               30977
#define L_CANTGIVE                  40
#define A_HELLO                  30959
#define L_HELLO                     18
#define A_ANUBIS                 30953
#define L_ANUBIS                     6
#define A_BES                    30950
#define L_BES                        3
#define A_KHONSU                 30944
#define L_KHONSU                     6
#define A_THOTH                  30939
#define L_THOTH                      5
#define A_PLEASED                30913
#define L_PLEASED                   26
#define A_NOTPOSSIBLE            30886
#define L_NOTPOSSIBLE               27
#define A_ERROR                  30820
#define L_ERROR                     66
