#define A_HELP                   31635
#define L_HELP                    1133
#define A_ALPHABET               31342
#define L_ALPHABET                 293
#define A_LOCATION               31332
#define L_LOCATION                  10
#define A_SPACE                  31331
#define L_SPACE                      1
#define A_LF                     31323
#define L_LF                         8
#define A_COMMA                  31321
#define L_COMMA                      2
#define A_PROMPT                 31319
#define L_PROMPT                     2
#define A_QUIT                   31234
#define L_QUIT                      85
#define A_LOOK                   31213
#define L_LOOK                      21
#define A_DONTSEE                31187
#define L_DONTSEE                   26
#define A_CANTLOOK               31165
#define L_CANTLOOK                  22
#define A_CANTENTER              31135
#define L_CANTENTER                 30
#define A_CANTOPEN               31108
#define L_CANTOPEN                  27
#define A_NOTCARRYING            31075
#define L_NOTCARRYING               33
#define A_NOSUCHOBJECT           31055
#define L_NOSUCHOBJECT              20
#define A_NOSUCHPERSON           31035
#define L_NOSUCHPERSON              20
#define A_WHYTALK                31005
#define L_WHYTALK                   30
#define A_CANTUSE                30979
#define L_CANTUSE                   26
#define A_CANTREAD               30952
#define L_CANTREAD                  27
#define A_CANTUSEITEM            30913
#define L_CANTUSEITEM               39
#define A_RESPONSE               30895
#define L_RESPONSE                  18
#define A_INCORRECT              30877
#define L_INCORRECT                 18
#define A_CARRYTWO               30788
#define L_CARRYTWO                  89
#define A_ALREADYCARRYING        30751
#define L_ALREADYCARRYING           37
#define A_NOWCARRING             30729
#define L_NOWCARRING                22
#define A_EMPTYHANDS             30691
#define L_EMPTYHANDS                38
#define A_DROPPING               30675
#define L_DROPPING                  16
#define A_RETURNING              30614
#define L_RETURNING                 61
#define A_IDDQDMSG               30554
#define L_IDDQDMSG                  60
#define A_CONGRATS               30468
#define L_CONGRATS                  86
#define A_CANTGIVE               30428
#define L_CANTGIVE                  40
#define A_HELLO                  30410
#define L_HELLO                     18
#define A_ANUBIS                 30404
#define L_ANUBIS                     6
#define A_BES                    30401
#define L_BES                        3
#define A_KHONSU                 30395
#define L_KHONSU                     6
#define A_THOTH                  30390
#define L_THOTH                      5
#define A_PLEASED                30364
#define L_PLEASED                   26
#define A_NOTPOSSIBLE            30337
#define L_NOTPOSSIBLE               27
#define A_ERROR                  30271
#define L_ERROR                     66
#define A_PRIEST                 30093
#define L_PRIEST                   178
#define A_PLEASEOFFER            30050
#define L_PLEASEOFFER               43
#define A_BADOFFERING            29989
#define L_BADOFFERING               61
#define A_YOURPART               29957
#define L_YOURPART                  32
#define A_IDLE                   29935
#define L_IDLE                      22
#define A_SALT                   29916
#define L_SALT                      19
#define A_HEXPREFIX              29914
#define L_HEXPREFIX                  2
#define A_DIGITS                 29898
#define L_DIGITS                    16
