#define A_HELP                   31665
#define L_HELP                    1103
#define A_ALPHABET               31382
#define L_ALPHABET                 283
#define A_LOCATION               31371
#define L_LOCATION                  11
#define A_SPACE                  31370
#define L_SPACE                      1
#define A_PROMPT                 31368
#define L_PROMPT                     2
#define A_QUIT                   31284
#define L_QUIT                      84
#define A_LOOK                   31262
#define L_LOOK                      22
#define A_COMMA                  31260
#define L_COMMA                      2
#define A_DONTSEE                31234
#define L_DONTSEE                   26
#define A_CANTLOOK               31212
#define L_CANTLOOK                  22
#define A_CANTENTER              31182
#define L_CANTENTER                 30
#define A_CANTOPEN               31155
#define L_CANTOPEN                  27
#define A_NOTCARRYING            31122
#define L_NOTCARRYING               33
#define A_NOSUCHOBJECT           31102
#define L_NOSUCHOBJECT              20
#define A_NOSUCHPERSON           31082
#define L_NOSUCHPERSON              20
#define A_WHYTALK                31052
#define L_WHYTALK                   30
#define A_CANTUSE                31026
#define L_CANTUSE                   26
#define A_CANTREAD               30999
#define L_CANTREAD                  27
#define A_CANTUSEITEM            30960
#define L_CANTUSEITEM               39
#define A_RESPONSE               30942
#define L_RESPONSE                  18
#define A_INCORRECT              30924
#define L_INCORRECT                 18
#define A_CARRYTWO               30836
#define L_CARRYTWO                  88
#define A_ALREADYCARRYING        30799
#define L_ALREADYCARRYING           37
#define A_NOWCARRING             30777
#define L_NOWCARRING                22
#define A_EMPTYHANDS             30739
#define L_EMPTYHANDS                38
#define A_DROPPING               30723
#define L_DROPPING                  16
#define A_RETURNING              30662
#define L_RETURNING                 61
#define A_IDDQDMSG               30602
#define L_IDDQDMSG                  60
#define A_CONGRATS               30517
#define L_CONGRATS                  85
#define A_CANTGIVE               30477
#define L_CANTGIVE                  40
#define A_HELLO                  30459
#define L_HELLO                     18
#define A_ANUBIS                 30453
#define L_ANUBIS                     6
#define A_BES                    30450
#define L_BES                        3
#define A_KHONSU                 30444
#define L_KHONSU                     6
#define A_THOTH                  30439
#define L_THOTH                      5
#define A_PLEASED                30413
#define L_PLEASED                   26
#define A_NOTPOSSIBLE            30386
#define L_NOTPOSSIBLE               27
#define A_ERROR                  30320
#define L_ERROR                     66
#define A_PRIEST                 30146
#define L_PRIEST                   174
#define A_BADOFFERING            30085
#define L_BADOFFERING               61
#define A_YOURPART               30053
#define L_YOURPART                  32