#!/usr/bin/env bash

python3 pyupdi/pyupdi.py -c /dev/ttyUSB0 -d tiny1617 -f hh2020.hex > outbuff 2>&1
if [ $? == 0 ]; then
  python3 pyupdi/pyupdi.py -c /dev/ttyUSB0 -d tiny1617 -fs 1:0x4C 5:0xF6 10:0x3A >> outbuff 2>&1
  if [ $? == 0 ]; then
    echo -e "\u001b[42m"
    clear
  else
    echo -e "\u001b[41m"
    clear
  fi
else
  echo -e "\u001b[41m"
  clear
fi
cat outbuff
