#define A_HELP                   31635
#define L_HELP                    1133
#define A_ALPHABET               31342
#define L_ALPHABET                 293
#define A_LOCATION               31330
#define L_LOCATION                  12
#define A_SPACE                  31329
#define L_SPACE                      1
#define A_LF                     31321
#define L_LF                         8
#define A_COMMA                  31319
#define L_COMMA                      2
#define A_PROMPT                 31317
#define L_PROMPT                     2
#define A_QUIT                   31232
#define L_QUIT                      85
#define A_LOOK                   31211
#define L_LOOK                      21
#define A_DONTSEE                31185
#define L_DONTSEE                   26
#define A_CANTLOOK               31163
#define L_CANTLOOK                  22
#define A_CANTENTER              31133
#define L_CANTENTER                 30
#define A_CANTOPEN               31106
#define L_CANTOPEN                  27
#define A_NOTCARRYING            31073
#define L_NOTCARRYING               33
#define A_NOSUCHOBJECT           31053
#define L_NOSUCHOBJECT              20
#define A_NOSUCHPERSON           31033
#define L_NOSUCHPERSON              20
#define A_WHYTALK                31003
#define L_WHYTALK                   30
#define A_CANTUSE                30977
#define L_CANTUSE                   26
#define A_CANTREAD               30950
#define L_CANTREAD                  27
#define A_CANTUSEITEM            30911
#define L_CANTUSEITEM               39
#define A_RESPONSE               30893
#define L_RESPONSE                  18
#define A_INCORRECT              30816
#define L_INCORRECT                 77
#define A_CARRYTWO               30727
#define L_CARRYTWO                  89
#define A_ALREADYCARRYING        30690
#define L_ALREADYCARRYING           37
#define A_NOWCARRING             30668
#define L_NOWCARRING                22
#define A_EMPTYHANDS             30630
#define L_EMPTYHANDS                38
#define A_DROPPING               30614
#define L_DROPPING                  16
#define A_RETURNING              30553
#define L_RETURNING                 61
#define A_IDDQDMSG               30493
#define L_IDDQDMSG                  60
#define A_CONGRATS               30407
#define L_CONGRATS                  86
#define A_CANTGIVE               30367
#define L_CANTGIVE                  40
#define A_HELLO                  30349
#define L_HELLO                     18
#define A_ANUBIS                 30343
#define L_ANUBIS                     6
#define A_BES                    30340
#define L_BES                        3
#define A_KHONSU                 30334
#define L_KHONSU                     6
#define A_THOTH                  30329
#define L_THOTH                      5
#define A_PLEASED                30303
#define L_PLEASED                   26
#define A_NOTPOSSIBLE            30276
#define L_NOTPOSSIBLE               27
#define A_ERROR                  30210
#define L_ERROR                     66
#define A_PRIEST                 30032
#define L_PRIEST                   178
#define A_PLEASEOFFER            29989
#define L_PLEASEOFFER               43
#define A_BADOFFERING            29928
#define L_BADOFFERING               61
#define A_YOURPART               29896
#define L_YOURPART                  32
#define A_IDLE                   29874
#define L_IDLE                      22
#define A_SALT                   29855
#define L_SALT                      19
#define A_HEXPREFIX              29853
#define L_HEXPREFIX                  2
#define A_DIGITS                 29837
#define L_DIGITS                    16
