#define A_HELP                   31665
#define L_HELP                    1103
#define A_ALPHABET               31382
#define L_ALPHABET                 283
#define A_LOCATION               31371
#define L_LOCATION                  11
#define A_SPACE                  31370
#define L_SPACE                      1
#define A_LF                     31366
#define L_LF                         4
#define A_COMMA                  31364
#define L_COMMA                      2
#define A_PROMPT                 31362
#define L_PROMPT                     2
#define A_QUIT                   31278
#define L_QUIT                      84
#define A_LOOK                   31256
#define L_LOOK                      22
#define A_DONTSEE                31230
#define L_DONTSEE                   26
#define A_CANTLOOK               31208
#define L_CANTLOOK                  22
#define A_CANTENTER              31178
#define L_CANTENTER                 30
#define A_CANTOPEN               31151
#define L_CANTOPEN                  27
#define A_NOTCARRYING            31118
#define L_NOTCARRYING               33
#define A_NOSUCHOBJECT           31098
#define L_NOSUCHOBJECT              20
#define A_NOSUCHPERSON           31078
#define L_NOSUCHPERSON              20
#define A_WHYTALK                31048
#define L_WHYTALK                   30
#define A_CANTUSE                31022
#define L_CANTUSE                   26
#define A_CANTREAD               30995
#define L_CANTREAD                  27
#define A_CANTUSEITEM            30956
#define L_CANTUSEITEM               39
#define A_RESPONSE               30938
#define L_RESPONSE                  18
#define A_INCORRECT              30920
#define L_INCORRECT                 18
#define A_CARRYTWO               30832
#define L_CARRYTWO                  88
#define A_ALREADYCARRYING        30795
#define L_ALREADYCARRYING           37
#define A_NOWCARRING             30773
#define L_NOWCARRING                22
#define A_EMPTYHANDS             30735
#define L_EMPTYHANDS                38
#define A_DROPPING               30719
#define L_DROPPING                  16
#define A_RETURNING              30658
#define L_RETURNING                 61
#define A_IDDQDMSG               30598
#define L_IDDQDMSG                  60
#define A_CONGRATS               30513
#define L_CONGRATS                  85
#define A_CANTGIVE               30473
#define L_CANTGIVE                  40
#define A_HELLO                  30455
#define L_HELLO                     18
#define A_ANUBIS                 30449
#define L_ANUBIS                     6
#define A_BES                    30446
#define L_BES                        3
#define A_KHONSU                 30440
#define L_KHONSU                     6
#define A_THOTH                  30435
#define L_THOTH                      5
#define A_PLEASED                30409
#define L_PLEASED                   26
#define A_NOTPOSSIBLE            30382
#define L_NOTPOSSIBLE               27
#define A_ERROR                  30316
#define L_ERROR                     66
#define A_PRIEST                 30142
#define L_PRIEST                   174
#define A_PLEASEOFFER            30099
#define L_PLEASEOFFER               43
#define A_BADOFFERING            30038
#define L_BADOFFERING               61
#define A_YOURPART               30006
#define L_YOURPART                  32
#define A_IDLE                   29984
#define L_IDLE                      22
#define A_SALT                   29965
#define L_SALT                      19
