name: Maak Firmware

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get prequisites
      run: sudo apt update && sudo apt install -y --no-install-recommends gcc-avr
    - name: Maak
      run: cd Working\ IO\ code/ && ./maak.sh
